### ISSUE TITLE
Non-minified dist files

### ISSUE THREAD

**Issue by enumag** [jahudka/nettejs#1]
I handle the minification myself because I only want to minify the files in production environment (but I always want to concatenate then into one). That means all files in the dist directory of this package are currently useless for me and I'd have to somehow use all (or nearly all) files from the src dir. While I probably will do that eventually anyway I'd like to avoid it for now since I'm not familiar with this library yet.

Could you update your Gruntfile.js to generate non-minified files as well? I'd send a pull request but sadly I'm not familiar with Grunt - I use Gulp instead.

**Comment by jahudka** [comment]
Fixed for now. I'm not sure this is the way though.. In a development environment you probably don't just want to use non-minified files, you also probably want a proper sourcemap, and you'd have to generate that yourself when you build your concatenated file - but if you only included NetteJS as a single file at that point you'd lose source mapping *within* NetteJS.. whereas if you use the individual files from 'src/' the sourcemap would be correct. On the other hand, it feels sort of weird to include a "development" package in the "dist" folder - for one thing, the "dist" folder is supposed to contain only final, production-ready packages, and for another, there already *is* a lot of "development" code in the 'src/' directory..

So the non-minified builds *will* disappear someday, I don't want to keep them long-term.

**Comment by enumag** [comment]
Yeah, I'm generating sourcemaps as well. Although admittedly I'm not entirely sure if they are generated correctly.

I know I'm losing source mapping within NetteJS - its the same with other libraries I'm using.

I'd like you to reconsider it. If you look to other CSS / JS libraries its pretty much standard to put both minified and non-minified variants into the dist dir.

As for Grunt, no thanks, I like Gulp much better! :-P

**Comment by enumag** [comment]
Also another note. Are you certain its correct to tag a new version after each commit? I've never seen that in any library. Also you did actually break compatibility with older versions just now because you renamed the files in the dist dir - nette.min.js => nette.core.min.js, nette.full.js still exists but was minified previously and is not anymore... Please consider [Semver](http://semver.org/) instead.

**Comment by jahudka** [comment]
I know other libraries do it, I'm just not sure I agree with it :-) yeah, it may be a little more convenient for developers to paste just one line into their build recipes instead of fifteen, but if something breaks for them because of a bug in nettejs, how are they supposed to know what to report, unless they get familiar enough with the nettejs code themselves?

Yes, I'm quite certain that I mostly know what I'm doing with the tags. As I've written and said in various places, NetteJS still isn't to be considered production ready; I'm trying hard to get there asap, but until then pretty much *every* commit may break compatibility, and pretty much every commit contains some bugfixes at the very least. 

So I want to mark most commits as new releases to let others know that beware, there may be changes here, better check it out before using. If I were to go with Semver right from the start, we wouldn't have version 1.0.65 now, but something like version 58.0.2, which would suck. After I get the first stable version out there, which would probably be version number 2.0.0 to avoid all confusion, I fully intend to start sticking to Semver :-)

**Comment by enumag** [comment]
Thanks for clarification! :-)

According to Semver initial development versions like this should be named 0.x.y but of course it's too late for that now.

**Comment by jahudka** [comment]
Yeah, well, as you say.. I got a bit overexcited ;-)

**Comment by enumag** [comment]
Also maybe you should add a note that this is not production-ready to readme and/or wiki. I didn't know until you said it here.

**Comment by jahudka** [comment]
Done.

Thanks :-) well I've started by stating that the documentation was lacking, and moved on to fill the gaps, so the original note might be outdated by now.. though I'm still not sure if it's actually *good*, it covers most of the code and features, but that doesn't necessarily mean it's *comprehensible*. That's something not easily assessed from the author's point of view :-)

And as an afterthought.. as it is, NetteJS is pretty much a large bundle that you can't easily separate - the Page service won't work without the Ajax service or the Forms service, the Forms service won't work without the FlashMessages widget etc - and in the long term I'd like to fix this, so that you can have independent individual packages and only include what you need in your project. Quite like how Nette is separated these days.. and I'm not sure how much sense it would then make to have the dist packages in the repository, minified or not, since you'll still need to use *some* sort of build setup to put everything together. I'm not saying that not including packaged versions at all is the way to go, just that I'm not really sure what *is*.. Thoughts? :-)

**Comment by jahudka** [comment]
Obviously by that time there'd also be a NetteJS website where you'd be able to download a custom package including everything you need, much like jQuery UI and similar libraries, for when you don't want or need to use Bower / Composer / ...

**Comment by enumag** [comment]
I'll let you know if I have any idea for improvements of the documentation. :-)

I'm not sure if separation is worth it for this project. Most CSS/JS libraries are in one repository even if they have many components. I believe that's a topic for a future discussion when this library will have more users.

That said separating dependencies is a good thing for sure. For example I don't use nette/forms so I probably won't need NetteJS/Forms either.
